# -*- coding: utf-8 -*-
"""First.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15U-BNIEneBZrGZYVxzXHmRPGOLbkrS6m
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = {
    'Name' : ['Harshita', 'Pooja', 'Jahnvi', 'Deepak', 'Shivkant', 'Anushka'],
    'Age' : [20, 19, 19, 25, 23, 20],
    'Department' : ['CS', 'IT', 'CS', 'CS', 'IT', 'IT']
}

data

sample_df = pd.DataFrame(data)
sample_df

sample_df.groupby(['Age','Name']).sum()

sample_df.groupby('Age')['Name'].apply(list)

sample_df.groupby(['Department', 'Age']).size()

sample_df.groupby('Age').first()

sample_df.groupby('Age').last()

sample_df.groupby('Age')['Name'].count()

sample_df.groupby('Department')['Age'].mean()

sample_df.groupby('Department')['Name'].unique()

sns.histplot(sample_df['Age'], kde=True)